### ISSUE TITLE
Failed to generate PDF: r.findLastIndex is not a function

### ISSUE THREAD

**Issue by andybuki** [jbaiter/pdiiif#24]
Hi Johanes,

i tried to generate a manifest in Firefox and got following issue:

"Failed to generate PDF: r.findLastIndex is not a function"

![image](https://github.com/jbaiter/pdiiif/assets/4548460/e1ca1618-7ac1-4397-b078-f54552ce82bd)

In Chrome it works correctly.

**Comment by andybuki** [comment]
Safari -> same issue

**Comment by jbaiter** [comment]
Just tried it with the latest Firefox version on https://pdiiif.jbaiter.de with the manifest from your example and it generated fine for me:
https://iiif.crossasia.org/s/dllm/madoc/api/manifests/20817/export/3.0
[Thammasangkini pakalana wohan (ທັມມະສັງຄິນີປະກະຣະນະໂວຫານ).pdf](https://github.com/jbaiter/pdiiif/files/11679148/Thammasangkini.pakalana.wohan.pdf)

**Comment by andybuki** [comment]
I just tried it on mac os safari/firefox -> everything works right.
I get this issue on Windows Firefox version 102.12.0 64 Bit.
Safari issue was one from users (I don't know the details)

**Comment by andybuki** [comment]
May be it can help i add image with an issue:

![image](https://github.com/jbaiter/pdiiif/assets/4548460/f87ff15b-dd66-49a5-b389-1fde87b5e799)

I just noticed that it adds semicolon to the link:

Error fetching https://iiif-content.crossasia.org/xasia/dllm+dllm_00011171+457165/full/full/0/default.jpg:
It works only without ":"

**Comment by jbaiter** [comment]
Can you ask your user which Safari version they're using? The error occurs during a call to `Uint8Array.lastIndxOf`, which has been part of Safari since version 10: https://caniuse.com/mdn-javascript_builtins_typedarray_lastindexof
If your user is still on Safari 9, I don't think there's much I can do for them, this is a modern web application and Safari 9 is an *ancient* browser (and a huge security risk) that last saw an update in 2016.

**Comment by jbaiter** [comment]
I'm pretty much at a loss at what could cause this. `Uint8Array.findLastIndex` has been part of Firefox since version 47, which was released in 2016. Can you try a few times and see if that changes things? Also, are you absolutely sure that this error occurs on Firefox 102?

**Comment by andybuki** [comment]
About Safari's version by some user i'll try to know tomorrow.
I'll try on other windows computer today and let you know too.
Here is a screenshot of my working mashine. All updates and most changes can do only admin.
![image](https://github.com/jbaiter/pdiiif/assets/4548460/0fbeeaa5-d787-4715-9d6f-84a83d3ebde0)

**Comment by jbaiter** [comment]
OK, I probably shouldn't analyze bugs immediately after a long day of work :-)
Turns out I had confused `TypedArray#findLastIndexOf` (which takes a predicate) with `TypedArray#findLastIndex` (which takes a value). The former has only been part of Firefox since version 104 and Safari 15.4 (from last year), so it's obviously not in Firefox 102 or older Safari versions.
I'll implement a polyfill for older versions, thank you for reporting the issue!

**Comment by andybuki** [comment]
I agree with you, it is an old versions. in other computer everything works right. Thanks for support.

**Comment by jbaiter** [comment]
Nono,I was mistaken in my earlier comments (due to me confusing it with a different function), browsers without `TypedArray#findLastIndex` are definitely not *old*, the API is just very new and I wasn't aware of that when writing the code. The next release will include the polyfill and it should work on more browsers :-)
