### ISSUE TITLE
Failed to generate PDF: navigator.locks is undefined

### ISSUE THREAD

**Issue by hxsllc** [jbaiter/pdiiif#29]
Hello! I've just tried out your code (finally 1 year after the 2022 conference) and I am running into an issue.

"Failed to generate PDF: navigator.locks is undefined"

This is a 2.1 manifest: https://data.metascripta.org/iiif/VFL_VTL_03177_01.json

Initially I had an @id mismatch and I got a "u is null" error, but then I tested with the validator and got it corrected.
http://presentation-validator.iiif.io/validate?version=2.1&url=https://data.metascripta.org/iiif/VFL_VTL_03177_01.json

Now when I try to generate PDF, I get the error above. It does successfully calculate the PDF size (some 800MB).

Any ideas? Running Docker on Mac OS Monterey (12.3.1).

<img width="1189" alt="Screen Shot 2023-06-09 at 3 42 32 AM" src="https://github.com/jbaiter/pdiiif/assets/29841283/cdde2324-6e23-443b-bbea-4612a9b9ccf0">

**Comment by jbaiter** [comment]
Can you check your Safari version (including the minor version after the dot)?
You're probably using an older Safari version that doesn't have support for the `navigator.lock` API (https://caniuse.com/mdn-api_navigator_locks).
I'll try to find a polyfill for the next release, but until then you might want to try updating your browser: The last version without support for the API was 15.3, which is no longer supported, so you might want to update regardless, since it's not receiving any security updates anymore.

**Comment by jbaiter** [comment]
Turns out the locking wasn't really needed after all, I've removed the calls to the `navigator.locks` API, it should work once the next release is done and deployed.
